name: Build and Deploy Open Quantum Safe

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

env:
  VCPKG_MANIFEST_DIR: ${{ github.workspace }}
  VCPKG_CACHE_DIR: ${{ github.workspace }}/vcpkg/vcpkg_installed
  VCPKG_BINARY_SOURCES: clear;nuget,GitHub,readwrite;files,${{ github.workspace }}/vcpkg/vcpkg_installed,readwrite

  CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
  CMAKE_SOURCE_ROOT: ${{ github.workspace }}/liboqs
  CMAKE_BUILD_ROOT: ${{ github.workspace }}/build

defaults:
  run:
    shell: pwsh

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_liboqs:
    name: Build liboqs
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [windows-2022, ubuntu-latest, macos-latest]
        arch: [x64, x86, arm, arm64]
        exclude:
          - os: ubuntu-latest
            arch: x86
          - os: macos-latest
            arch: x86
          - os: macos-latest
            arch: arm
          - os: macos-latest
            arch: arm64
        include:
          - os: windows-2022
            arch: x64
            install:
              - New-Item -Path `"${env:VCPKG_CACHE_DIR}`" -ItemType Directory -Force
            liboqs:
              cmake_generator: Ninja
              cmake_build_type: Release
              cmake_target_triplet: x64-mingw-static
              cmake_toolchain_file: ""
              cmake_install_prefix: runtimes/win-x64/native
              use_msvc: false
              msvc_environment: vcvars64
              use_msys2: true
              msys2_environment: MINGW64
              msys2_install: >-
                mingw-w64-x86_64-toolchain
                mingw-w64-x86_64-cmake
                mingw-w64-x86_64-ninja
              use_gcc: false
              gcc_cc: ""
              gcc_cxx: ""

          - os: windows-2022
            arch: x86
            install:
              - New-Item -Path `"${env:VCPKG_CACHE_DIR}`" -ItemType Directory -Force
            liboqs:
              cmake_generator: Ninja
              cmake_build_type: Release
              cmake_target_triplet: x86-mingw-static
              cmake_toolchain_file: ""
              cmake_install_prefix: runtimes/win-x86/native
              use_msvc: false
              msvc_environment: vcvars32
              use_msys2: true
              msys2_environment: MINGW32
              msys2_install: >-
                mingw-w64-i686-toolchain
                mingw-w64-i686-cmake
                mingw-w64-i686-ninja
              use_gcc: false
              gcc_cc: ""
              gcc_cxx: ""

          - os: windows-2022
            arch: arm
            install:
              - New-Item -Path `"${env:VCPKG_CACHE_DIR}`" -ItemType Directory -Force
            liboqs:
              cmake_generator: Ninja
              cmake_build_type: Release
              cmake_target_triplet: arm-windows-static
              cmake_toolchain_file: ""
              cmake_install_prefix: runtimes/win-arm/native
              use_msvc: true
              msvc_environment: vcvarsamd64_arm
              use_msys2: false
              msys2_environment: ""
              msys2_install: ""
              use_gcc: false
              gcc_cc: ""
              gcc_cxx: ""

          - os: windows-2022
            arch: arm64
            install:
              - New-Item -Path `"${env:VCPKG_CACHE_DIR}`" -ItemType Directory -Force
            liboqs:
              cmake_generator: Ninja
              cmake_build_type: Release
              cmake_target_triplet: arm64-windows-static
              cmake_toolchain_file: ""
              cmake_install_prefix: runtimes/win-arm64/native
              use_msvc: true
              msvc_environment: vcvarsamd64_arm64
              use_msys2: false
              msys2_environment: ""
              msys2_install: ""
              use_gcc: false
              gcc_cc: ""
              gcc_cxx: ""

          - os: ubuntu-latest
            arch: x64
            install:
              - sudo apt-get update -y
              - sudo apt-get install curl zip unzip tar p7zip-full cmake ninja-build build-essential pkg-config gcc-10 g++-10 -y
              - New-Item -Path `"${env:VCPKG_CACHE_DIR}`" -ItemType Directory -Force
            liboqs:
              cmake_generator: Ninja
              cmake_build_type: Release
              cmake_target_triplet: x64-linux
              cmake_toolchain_file: ""
              cmake_install_prefix: runtimes/linux-x64/native
              use_msvc: false
              msvc_environment: ""
              use_msys2: false
              msys2_environment: ""
              msys2_install: ""
              use_gcc: true
              gcc_cc: gcc-10
              gcc_cxx: g++-10

          - os: ubuntu-latest
            arch: arm
            install:
              - sudo apt-get update -y
              - sudo apt-get install curl zip unzip tar p7zip-full cmake ninja-build build-essential pkg-config gcc-10-arm-linux-gnueabihf g++-10-arm-linux-gnueabihf -y
              - New-Item -Path `"${env:VCPKG_CACHE_DIR}`" -ItemType Directory -Force
            liboqs:
              cmake_generator: Ninja
              cmake_build_type: Release
              cmake_target_triplet: arm-linux
              cmake_toolchain_file: cmake/raspberrypi-arm.cmake
              cmake_install_prefix: runtimes/linux-arm/native
              use_msvc: false
              msvc_environment: ""
              use_msys2: false
              msys2_environment: ""
              msys2_install: ""
              use_gcc: true
              gcc_cc: gcc-10
              gcc_cxx: g++-10

          - os: ubuntu-latest
            arch: arm64
            install:
              - sudo apt-get update -y
              - sudo apt-get install curl zip unzip tar p7zip-full cmake ninja-build build-essential pkg-config gcc-10-aarch64-linux-gnu g++-10-aarch64-linux-gnu -y
              - New-Item -Path `"${env:VCPKG_CACHE_DIR}`" -ItemType Directory -Force
            liboqs:
              cmake_generator: Ninja
              cmake_build_type: Release
              cmake_target_triplet: arm64-linux
              cmake_toolchain_file: cmake/raspberrypi-arm64.cmake
              cmake_install_prefix: runtimes/linux-arm64/native
              use_msvc: false
              msvc_environment: ""
              use_msys2: false
              msys2_environment: ""
              msys2_install: ""
              use_gcc: true
              gcc_cc: gcc-10
              gcc_cxx: g++-10

          - os: macos-latest
            arch: x64
            install:
              - brew update
              - brew install ninja
              - New-Item -Path `"${env:VCPKG_CACHE_DIR}`" -ItemType Directory -Force
            liboqs:
              cmake_generator: Ninja
              cmake_build_type: Release
              cmake_target_triplet: x64-osx
              cmake_toolchain_file: ""
              cmake_install_prefix: runtimes/osx-x64/native
              use_msvc: false
              msvc_environment: ""
              use_msys2: false
              msys2_environment: ""
              msys2_install: ""
              use_gcc: true
              gcc_cc: gcc-10
              gcc_cxx: g++-10

    steps:
      # Init
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Install
      - name: Install Program / Dependencies
        if: join(matrix.install, ' && ')
        run: |
          Invoke-Expression "${{ join(matrix.install, ' && ') }}"

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          appendedCacheKey: ${{ runner.os }}-${{ matrix.arch }}

      - name: Setup NuGet Credentials
        run: |
          $vcpkg_executable = Join-Path "${{ env.VCPKG_ROOT }}" 'vcpkg'
          $mono = "${{ runner.os }}" -eq 'Windows' ? '' : 'mono'

          $nuget_executable = @(Invoke-Expression "$vcpkg_executable fetch nuget") | Select-Object -Last 1
          Invoke-Expression "$mono $nuget_executable sources add -source `"https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json`" -storepasswordincleartext -name `"GitHub`" -username `"${{ github.repository_owner }}`" -password `"${{ secrets.GITHUB_TOKEN }}`""

      - name: Setup msys2 environemnt
        uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows' && matrix.liboqs.use_msys2
        with:
          update: true
          install: ${{ matrix.liboqs.msys2_install }}

      # Build liboqs
      - name: Build liboqs
        run: |
          $cmake_chainload_toolchain_file = Join-Path "${{ github.workspace }}" "${{ matrix.liboqs.cmake_toolchain_file }}"
          $cmake_install_prefix = Join-Path "${{ github.workspace }}" "${{ matrix.liboqs.cmake_install_prefix }}"

          if ("${{ runner.os }}" -eq 'Windows')
          {
            $cmake_chainload_toolchain_file = $cmake_chainload_toolchain_file.Replace('\', '/')
            $cmake_install_prefix = $cmake_install_prefix.Replace('\', '/')

            if ("${{ matrix.liboqs.use_msvc }}" -eq 'true')
            {
              $msbuild_install_root = Join-Path "${{ env.CMAKE_BUILD_ROOT }}" 'INSTALL.vcxproj'
              cmd /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\${{ matrix.liboqs.msvc_environment }}.bat`" && cmake -G `"${{ matrix.liboqs.cmake_generator }}`" -DCMAKE_BUILD_TYPE=`"${{ matrix.liboqs.cmake_build_type }}`" -DCMAKE_TOOLCHAIN_FILE=`"${{ env.CMAKE_TOOLCHAIN_FILE }}`" -DVCPKG_TARGET_TRIPLET=`"${{ matrix.liboqs.cmake_target_triplet }}`" -DVCPKG_MANIFEST_DIR=`"${{ env.VCPKG_MANIFEST_DIR }}`" -DCMAKE_INSTALL_PREFIX=`"$cmake_install_prefix`" -DBUILD_SHARED_LIBS=`"ON`" -DOQS_BUILD_ONLY_LIB=`"ON`" -DOQS_DIST_BUILD=`"ON`" -DOQS_USE_OPENSSL=`"ON`" -S `"${{ env.CMAKE_SOURCE_ROOT }}`" -B `"${{ env.CMAKE_BUILD_ROOT }}`" && ninja -C `"${{ env.CMAKE_BUILD_ROOT }}`" install"
            }
            elseif ("${{ matrix.liboqs.use_msys2 }}" -eq 'true')
            {
              $env:MSYSTEM = "${{ matrix.liboqs.msys2_environment }}"

              msys2 -c "cmake -G `"${{ matrix.liboqs.cmake_generator }}`" -DCMAKE_BUILD_TYPE=`"${{ matrix.liboqs.cmake_build_type}}`" -DCMAKE_TOOLCHAIN_FILE=`"${{ env.CMAKE_TOOLCHAIN_FILE }}`" -DVCPKG_TARGET_TRIPLET=`"${{ matrix.liboqs.cmake_target_triplet}}`" -DVCPKG_MANIFEST_DIR=`"${{ env.VCPKG_MANIFEST_DIR }}`" -DCMAKE_INSTALL_PREFIX=`"$cmake_install_prefix`" -DBUILD_SHARED_LIBS=`"ON`" -DOQS_BUILD_ONLY_LIB=`"ON`" -DOQS_DIST_BUILD=`"ON`" -DOQS_USE_OPENSSL=`"ON`" -S `"${{ env.CMAKE_SOURCE_ROOT }}`" -B `"${{ env.CMAKE_BUILD_ROOT }}`""
              msys2 -c "ninja -C `"${{ env.CMAKE_BUILD_ROOT }}`" install"
            }
          }
          else
          {
            if (![string]::IsNullOrWhiteSpace("${{ matrix.liboqs.cmake_toolchain_file }}"))
            {
              cmake -G "${{ matrix.liboqs.cmake_generator }}" -DCMAKE_BUILD_TYPE="${{ matrix.liboqs.cmake_build_type}}" -DCMAKE_TOOLCHAIN_FILE="${{ env.CMAKE_TOOLCHAIN_FILE }}" -DVCPKG_TARGET_TRIPLET="${{ matrix.liboqs.cmake_target_triplet}}" -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE="$cmake_chainload_toolchain_file" -DVCPKG_MANIFEST_DIR=`"${{ env.VCPKG_MANIFEST_DIR }}`" -DCMAKE_INSTALL_PREFIX="$cmake_install_prefix" -DBUILD_SHARED_LIBS=`"ON`" -DOQS_BUILD_ONLY_LIB=`"ON`" -DOQS_DIST_BUILD=`"ON`" -DOQS_USE_OPENSSL=`"ON`" -S "${{ env.CMAKE_SOURCE_ROOT }}" -B "${{ env.CMAKE_BUILD_ROOT }}"
            }
            else
            {
              $env:CC = "${{ matrix.liboqs.gcc_cc }}"
              $env:CXX = "${{ matrix.liboqs.gcc_cxx }}"

              cmake -G "${{ matrix.liboqs.cmake_generator }}" -DCMAKE_BUILD_TYPE="${{ matrix.liboqs.cmake_build_type}}" -DCMAKE_TOOLCHAIN_FILE="${{ env.CMAKE_TOOLCHAIN_FILE }}" -DVCPKG_TARGET_TRIPLET="${{ matrix.liboqs.cmake_target_triplet}}" -DVCPKG_MANIFEST_DIR=`"${{ env.VCPKG_MANIFEST_DIR }}`" -DCMAKE_INSTALL_PREFIX="$cmake_install_prefix" -DBUILD_SHARED_LIBS=`"ON`" -DOQS_BUILD_ONLY_LIB=`"ON`" -DOQS_DIST_BUILD=`"ON`" -DOQS_USE_OPENSSL=`"ON`" -S "${{ env.CMAKE_SOURCE_ROOT }}" -B "${{ env.CMAKE_BUILD_ROOT }}"
            }

            ninja -C "${{ env.CMAKE_BUILD_ROOT }}" install
          }

      # Package
      - name: Package liboqs
        run: |
          $publish_root = Join-Path "${{ github.workspace }}" '${{ matrix.liboqs.cmake_install_prefix }}'
          Set-Location "$publish_root"

          if ("${{ runner.os }}" -eq 'Windows')
          {
            Invoke-Expression "7z a -mx=9 `"${{ runner.os }}-${{ matrix.arch }}.zip`" ."
          }
          else
          {
            Invoke-Expression "7z a `"${{ runner.os }}-${{ matrix.arch }}.tar`" ."
            Invoke-Expression "7z a -sdel -mx=9 `"${{ runner.os }}-${{ matrix.arch }}.tar.gz`" `"${{ runner.os }}-${{ matrix.arch }}.tar`""
          }

      # Upload Artifacts
      - name: Upload liboqs artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-${{ matrix.arch }}
          path: |
            ${{ github.workspace }}/${{ matrix.liboqs.cmake_install_prefix }}/*.*
